### ISSUE TITLE
Uncaught TypeError when setting leaveHiddenModal to false on MDBModal

### ISSUE THREAD

**Issue by JohannesHansen** [mdbootstrap/mdb-react-ui-kit#182]
Setting leaveHiddenModal to false triggers the following error.

`react-dom.development.js:22834 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at eval (mdb-react-ui-kit.esm.js:1402:18)
    at commitHookEffectListMount (react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24873:7)
    at commitPassiveMountEffects (react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27034:3)
    at flushPassiveEffects (react-dom.development.js:26979:14)
    at performSyncWorkOnRoot (react-dom.development.js:26071:3)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at commitRootImpl (react-dom.development.js:26954:3)
    at commitRoot (react-dom.development.js:26677:5)
    at finishConcurrentRender (react-dom.development.js:25976:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:25804:7)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)`

**Comment by mako3577** [comment]
Sorry for delayed answer. I was able to reproduce the problem and can confirm a bug. We will fix it soon.
